Enroporra\EnroporraBundle\Entity\Apuesta:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        id_porrista:
            type: integer
        id_partido:
            type: integer
        id_competicion:
            type: integer
        resultado1:
            type: smallint
        resultado2:
            type: smallint
        id_equipo1:
            type: integer
        id_equipo2:
            type: integer
        quiniela:
            type: integer
    lifecycleCallbacks: {  }
