Enroporra\EnroporraBundle\Entity\Competicion:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '64'
        fecha_comienzo_primera_fase:
            type: datetime
        fecha_fin_primera_fase:
            type: datetime
        fecha_comienzo_segunda_fase:
            type: datetime
    lifecycleCallbacks: {  }
