Enroporra\EnroporraBundle\Entity\Partido:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        fecha:
            type: date
        hora:
            type: time
        id_competicion:
            type: integer
        fase:
            type: integer
        id_equipo1:
            type: integer
        id_equipo2:
            type: integer
        resultado1:
            type: integer
        resultado2:
            type: integer
        quiniela:
            type: integer
    lifecycleCallbacks: {  }
