parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: enroporra2
    database_user: root
    database_password: miguel
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: es
    secret: 7d00af71719af0731e7c0b8533f612ae6d579eea
    contact_email: comisionporra@gmail.com