#EnroporraBundle:
#    resource: "@EnroporraBundle/Resources/config/routing.yml"
#    prefix:   /

_home:
    pattern:  /
    defaults: { _controller: EnroporraBundle:Default:index }

_clasificacion:
    pattern:  /clasificacion
    defaults: { _controller: EnroporraBundle:Clasificacion:index }

_amigos:
    pattern:  /amigos
    defaults: { _controller: EnroporraBundle:Clasificacion:amigos }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
