parameters:
#    enroporra.example.class: Enroporra\Bundle\EnroporraBundle\Example

services:
#    enroporra.example:
#        class: %enroporra.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
