#parameters:
    #enroporra.tildes.class: Enroporra\EnroporraBundle\Globales\ApellidosConTilde

services:
    enroporra.base:
        class: Enroporra\EnroporraBundle\Globales\BaseEnroporra
    enroporra.apellidos_con_tilde:
        class: Enroporra\EnroporraBundle\Globales\ApellidosConTilde
#        arguments: [@service_id, "plain_value", %parameter%]
