parameters:
    enroporra.apellidos_con_tilde.class: Enroporra\EnroporraBundle\Globales\ApellidosConTilde

services:
    enroporra.apellidos_con_tilde:
        class: %enroporra.apellidos_con_tilde.class%
#        arguments: [@service_id, "plain_value", %parameter%]
