parameters:
    #enroporra.tildes.class: Enroporra\EnroporraBundle\Globales\ApellidosConTilde

services:
    apellidos_con_tilde:
        class: Enroporra\EnroporraBundle\Globales\ApellidosConTilde
#        arguments: [@service_id, "plain_value", %parameter%]
